### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by jurandfantom** [pbz134/VALL-E-X-portable#1]
Sorry pbz134, looks like portable or not, it is not system error proof. here is code I can see when run it 

`default encoding is utf-8,file system encoding is utf-8
You are using Python version 3.10.13
Use 32 cpu cores for computing
torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "huggingface_hub\utils\_errors.py", line 286, in hf_raise_for_status
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/charactr/vocos-encodec-24khz/resolve/main/config.yaml

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "huggingface_hub\file_download.py", line 1238, in hf_hub_download
  File "huggingface_hub\utils\_validators.py", line 118, in _inner_fn
  File "huggingface_hub\file_download.py", line 1631, in get_hf_file_metadata
  File "huggingface_hub\file_download.py", line 385, in _request_wrapper
  File "huggingface_hub\file_download.py", line 409, in _request_wrapper
  File "huggingface_hub\utils\_errors.py", line 333, in hf_raise_for_status
huggingface_hub.utils._errors.HfHubHTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/charactr/vocos-encodec-24khz/resolve/main/config.yaml

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "launch-ui.py", line 108, in <module>
  File "vocos\pretrained.py", line 67, in from_pretrained
  File "huggingface_hub\utils\_validators.py", line 118, in _inner_fn
  File "huggingface_hub\file_download.py", line 1371, in hf_hub_download
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
[89096] Failed to execute script 'launch-ui' due to unhandled exception!`

**Comment by pbz134** [comment]
What were you trying to do when this happened?
Usually, it should all work fine, as I tested it.
